version: '3.1'

services:

  mongo:
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express
    restart
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ualaDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8085:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: admin

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'

  user_service:
    image: user_service:latest
    restart: always
    ports:
      - "8081:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_APPLICATION_NAME: userService
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ualaDB
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_CACHE_TYPE: redis
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CACHE: DEBUG

  timeline_service:
    image: timeline_service:latest
    restart: always
    ports:
      - "8083:8080"
    environment:
      SERVER_PORT: 8080
      baseUserUrl: http://user_service:8081/
      baseTweetUrl: http://tweet_service:8082/
      JAVA_TOOL_OPTIONS: "--add-opens=java.base/java.time=ALL-UNNAMED"

  tweet_service:
    image: tweet_service:latest
    restart: always
    ports:
      - "8082:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_APPLICATION_NAME: tweet
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_USERNAME: admin
      SPRING_DATA_MONGODB_PASSWORD: admin
      SPRING_DATA_MONGODB_DATABASE: ualaDB
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin